#!/usr/bin/env python3

import os
import json
import sys
from pathlib import Path

class ProductionConfig:
    """Production configuration manager for Voice Query Agent"""
    
    def __init__(self):
        self.config_file = Path(".env")
        self.required_vars = {
            "GOOGLE_CLOUD_TOKEN": "Google Cloud access token",
            "GOOGLE_CLOUD_PROJECT_ID": "Google Cloud project ID", 
            "TWILIO_ACCOUNT_SID": "Twilio account SID",
            "TWILIO_AUTH_TOKEN": "Twilio auth token",
            "TWILIO_PHONE_NUMBER": "Twilio phone number",
            "WEBHOOK_BASE_URL": "Public webhook base URL"
        }
        self.optional_vars = {
            "GEMINI_MODEL": "gemini-2.0-flash-live-preview-04-09",
            "API_HOST": "us-central1-aiplatform.googleapis.com",
            "BACKEND_URL": "wss://localhost:8080",
            "SERVICE_ACCOUNT_KEY": "service-account-key.json",
            "PORT": "8080",
            "BIND_HOST": "0.0.0.0"
        }
    
    def check_configuration(self):
        """Check if all required configuration is present"""
        print("🔧 Checking Production Configuration")
        print("=" * 50)
        
        missing_vars = []
        warnings = []
        
        # Check required variables
        for var, description in self.required_vars.items():
            value = os.getenv(var)
            if not value or value.startswith("your_"):
                missing_vars.append((var, description))
                print(f"❌ {var}: Missing or placeholder value")
            else:
                print(f"✅ {var}: Configured")
        
        # Check optional variables
        for var, default in self.optional_vars.items():
            value = os.getenv(var)
            if not value:
                warnings.append((var, default))
                print(f"⚠️  {var}: Using default ({default})")
            else:
                print(f"✅ {var}: {value}")
        
        # Check webhook URL format
        webhook_url = os.getenv("WEBHOOK_BASE_URL", "")
        if webhook_url and not webhook_url.startswith("https://"):
            warnings.append(("WEBHOOK_BASE_URL", "Should use HTTPS for production"))
        
        # Summary
        print(f"\n📋 Configuration Summary:")
        if missing_vars:
            print(f"❌ Missing {len(missing_vars)} required variables")
            for var, desc in missing_vars:
                print(f"   - {var}: {desc}")
        else:
            print("✅ All required variables configured")
        
        if warnings:
            print(f"⚠️  {len(warnings)} warnings")
            for var, issue in warnings:
                print(f"   - {var}: {issue}")
        
        return len(missing_vars) == 0
    
    def setup_twilio_configuration(self):
        """Interactive setup for Twilio configuration"""
        print("\n📞 Twilio Configuration Setup")
        print("=" * 40)
        
        print("Please provide your Twilio credentials:")
        print("(You can find these in your Twilio Console)")
        
        account_sid = input("Twilio Account SID: ").strip()
        auth_token = input("Twilio Auth Token: ").strip()
        phone_number = input("Twilio Phone Number (e.g., +1234567890): ").strip()
        webhook_url = input("Public Webhook URL (e.g., https://yourdomain.com): ").strip()
        
        # Update .env file
        self.update_env_file({
            "TWILIO_ACCOUNT_SID": account_sid,
            "TWILIO_AUTH_TOKEN": auth_token,
            "TWILIO_PHONE_NUMBER": phone_number,
            "WEBHOOK_BASE_URL": webhook_url
        })
        
        print("\n✅ Twilio configuration saved to .env file")
        
        # Generate Twilio webhook configuration
        self.generate_twilio_setup_guide(webhook_url)
    
    def update_env_file(self, updates):
        """Update .env file with new values"""
        # Read existing content
        env_content = {}
        if self.config_file.exists():
            with open(self.config_file, 'r') as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith('#') and '=' in line:
                        key, value = line.split('=', 1)
                        env_content[key] = value
        
        # Update with new values
        env_content.update(updates)
        
        # Write back to file
        with open(self.config_file, 'w') as f:
            f.write("# Voice Query Agent Configuration\n")
            f.write("# Generated by production setup\n\n")
            
            f.write("# Google Cloud Configuration\n")
            for key in ["GOOGLE_CLOUD_TOKEN", "GOOGLE_CLOUD_PROJECT_ID", "GEMINI_MODEL", "API_HOST", "SERVICE_ACCOUNT_KEY"]:
                if key in env_content:
                    f.write(f"{key}={env_content[key]}\n")
            
            f.write("\n# Twilio Configuration\n")
            for key in ["TWILIO_ACCOUNT_SID", "TWILIO_AUTH_TOKEN", "TWILIO_PHONE_NUMBER", "WEBHOOK_BASE_URL"]:
                if key in env_content:
                    f.write(f"{key}={env_content[key]}\n")
            
            f.write("\n# Server Configuration\n")
            for key in ["BACKEND_URL", "PORT", "BIND_HOST"]:
                if key in env_content:
                    f.write(f"{key}={env_content[key]}\n")
    
    def generate_twilio_setup_guide(self, webhook_url):
        """Generate Twilio setup guide"""
        guide_file = Path("TWILIO_SETUP_GUIDE.md")
        
        content = f"""# Twilio Phone Number Configuration Guide

## Webhook Configuration

Configure your Twilio phone number with these settings:

### Voice Configuration
- **Webhook URL**: `{webhook_url}/incoming-call`
- **HTTP Method**: `POST`
- **Fallback URL**: `{webhook_url}/call-status`

### Media Streams
- **Media Stream URL**: `{webhook_url.replace('https://', 'wss://').replace('http://', 'ws://')}:8083/media-stream`

## Steps to Configure

1. **Log in to Twilio Console**
   - Go to https://console.twilio.com/
   - Navigate to Phone Numbers > Manage > Active numbers

2. **Select Your Phone Number**
   - Click on your purchased phone number

3. **Configure Voice Settings**
   - Set "A call comes in" webhook to: `{webhook_url}/incoming-call`
   - Set HTTP method to: `POST`
   - Set "Primary handler fails" to: `{webhook_url}/call-status`

4. **Save Configuration**
   - Click "Save configuration"

## Testing Your Setup

1. **Start the Voice Query Agent**:
   ```bash
   ./start-production.sh
   ```

2. **Verify Services**:
   ```bash
   python health_monitor.py
   ```

3. **Make a Test Call**:
   - Call your Twilio phone number
   - You should hear: "Hello! You are now connected to the voice agent..."

## Troubleshooting

- **Webhook not receiving calls**: Check that your server is publicly accessible
- **Audio not working**: Verify media stream WebSocket is reachable
- **Service errors**: Check logs in the `logs/` directory

## Security Notes

- Use HTTPS for all webhook URLs in production
- Keep your Twilio Auth Token secure
- Consider IP whitelisting for webhook endpoints
"""
        
        with open(guide_file, 'w') as f:
            f.write(content)
        
        print(f"\n📋 Setup guide saved to: {guide_file}")
        print(f"🔗 Webhook URL to configure in Twilio: {webhook_url}/incoming-call")
    
    def validate_production_readiness(self):
        """Validate system is ready for production"""
        print("\n🎯 Production Readiness Check")
        print("=" * 40)
        
        checks = []
        
        # Configuration check
        config_ok = self.check_configuration()
        checks.append(("Configuration", config_ok))
        
        # File permissions check
        scripts = ["start-production.sh", "health_monitor.py", "performance_test.py"]
        files_ok = all(Path(script).exists() for script in scripts)
        checks.append(("Required files", files_ok))
        
        # Dependencies check
        try:
            import numpy, websockets, fastapi, twilio
            deps_ok = True
        except ImportError:
            deps_ok = False
        checks.append(("Dependencies", deps_ok))
        
        # Print results
        all_ok = True
        for check_name, status in checks:
            if status:
                print(f"✅ {check_name}: Ready")
            else:
                print(f"❌ {check_name}: Not ready")
                all_ok = False
        
        if all_ok:
            print(f"\n🚀 System is READY for production!")
            print(f"   Start with: ./start-production.sh")
        else:
            print(f"\n⚠️  System needs attention before production deployment")
        
        return all_ok

def main():
    """Main configuration setup"""
    config = ProductionConfig()
    
    if len(sys.argv) > 1:
        command = sys.argv[1]
        
        if command == "check":
            config.check_configuration()
        elif command == "setup":
            config.setup_twilio_configuration()
        elif command == "validate":
            config.validate_production_readiness()
        else:
            print("Usage: python production_config.py [check|setup|validate]")
    else:
        # Interactive setup
        print("🔧 Voice Query Agent - Production Setup")
        print("=" * 50)
        
        if not config.check_configuration():
            print("\n❓ Would you like to set up Twilio configuration? (y/n): ", end="")
            if input().lower().startswith('y'):
                config.setup_twilio_configuration()
        
        config.validate_production_readiness()

if __name__ == "__main__":
    main()
